version: "3"
services:
  web:
    build: ./docker/web/
    platform: linux/amd64
    hostname: web-server
    volumes:
      - ./:/var/www/html
      - ./docker/web/root:/root
      - ./docker/web/workspace:/workspace
    ports:
      - 8080:80
      - 8443:443
    tty: true
  db:
    build: ./docker/db/
    platform: linux/amd64
    hostname: db-server
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./docker/db/root:/root
      - ./docker/db/workspace:/workspace
    ports:
      - 3307:3306
    tty: true
